POST http://localhost:80/api/item
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

POST http://localhost:8080/api/crawling/test



#####

POST http://localhost:8080/api/crawling/johns
#####
GET https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6


####
POST http://localhost:8080/api/crawling/deezer

####
POST http://localhost:8080/api/crawling/deezer